import urllib.request
import json
import time

url = "http://localhost:11434/api/generate"
model_name = "my_sql_model_v2:latest"

questions = [
    "Tables: CREATE TABLE employees (id INT, name VARCHAR, department VARCHAR, salary INT, hire_date DATE)\\nQuestion: What is the name of the employee with id 5?",
    "Tables: CREATE TABLE employees (id INT, name VARCHAR, department VARCHAR, salary INT, hire_date DATE)\\nQuestion: How many employees are in the IT department?",
    "Tables: CREATE TABLE employees (id INT, name VARCHAR, department VARCHAR, salary INT, hire_date DATE)\\nQuestion: Which department has the highest average salary?",
    "Tables: CREATE TABLE employees (id INT, name VARCHAR, department VARCHAR, salary INT, hire_date DATE)\\nQuestion: Find the names of employees who earn more than the average salary of their own department.",
    "Tables: CREATE TABLE students (student_id INT, name VARCHAR, major VARCHAR, gpa FLOAT, age INT)\\nQuestion: Show all students named 'John'.",
    "Tables: CREATE TABLE students (student_id INT, name VARCHAR, major VARCHAR, gpa FLOAT, age INT)\\nQuestion: What is the average GPA of students in the 'Computer Science' major?",
    "Tables: CREATE TABLE students (student_id INT, name VARCHAR, major VARCHAR, gpa FLOAT, age INT)\\nQuestion: List the majors that have more than 100 students.",
    "Tables: CREATE TABLE students (student_id INT, name VARCHAR, major VARCHAR, gpa FLOAT, age INT)\\nQuestion: What is the name of the youngest student who has the highest GPA in the 'Physics' major?",
    "Tables: CREATE TABLE products (product_id INT, name VARCHAR, category VARCHAR, price FLOAT, stock INT)\\nQuestion: What is the price of the product named 'iPhone'?",
    "Tables: CREATE TABLE products (product_id INT, name VARCHAR, category VARCHAR, price FLOAT, stock INT)\\nQuestion: Show the top 5 most expensive products.",
    "Tables: CREATE TABLE products (product_id INT, name VARCHAR, category VARCHAR, price FLOAT, stock INT)\\nQuestion: List all categories that have less than 50 items in total stock.",
    "Tables: CREATE TABLE products (product_id INT, name VARCHAR, category VARCHAR, price FLOAT, stock INT)\\nQuestion: Find the products whose price is higher than the average price of products in their respective category.",
    "Tables: CREATE TABLE orders (order_id INT, customer_id INT, product_id INT, order_date DATE, amount FLOAT)\\nQuestion: Show the order details for order_id 101.",
    "Tables: CREATE TABLE orders (order_id INT, customer_id INT, product_id INT, order_date DATE, amount FLOAT)\\nQuestion: What is the total amount of orders placed on '2023-01-01'?",
    "Tables: CREATE TABLE orders (order_id INT, customer_id INT, product_id INT, order_date DATE, amount FLOAT)\\nQuestion: Which customer has the highest total order amount?",
    "Tables: CREATE TABLE orders (order_id INT, customer_id INT, product_id INT, order_date DATE, amount FLOAT)\\nQuestion: Find the customer_id of the customer who ordered the most distinct products.",
    "Tables: CREATE TABLE movies (movie_id INT, title VARCHAR, director VARCHAR, release_year INT, rating FLOAT)\\nQuestion: What is the rating of the movie 'The Dark Knight'?",
    "Tables: CREATE TABLE movies (movie_id INT, title VARCHAR, director VARCHAR, release_year INT, rating FLOAT)\\nQuestion: Count how many movies were released in 2015.",
    "Tables: CREATE TABLE movies (movie_id INT, title VARCHAR, director VARCHAR, release_year INT, rating FLOAT)\\nQuestion: Show the names of directors who have directed more than 5 movies.",
    "Tables: CREATE TABLE movies (movie_id INT, title VARCHAR, director VARCHAR, release_year INT, rating FLOAT)\\nQuestion: Find the director who has the highest average rating for their movies released after 2000.",
    "Tables: CREATE TABLE cars (car_id INT, make VARCHAR, model VARCHAR, year INT, color VARCHAR)\\nQuestion: Show the color of the car model 'Civic'.",
    "Tables: CREATE TABLE cars (car_id INT, make VARCHAR, model VARCHAR, year INT, color VARCHAR)\\nQuestion: How many 'Toyota' cars are there?",
    "Tables: CREATE TABLE cars (car_id INT, make VARCHAR, model VARCHAR, year INT, color VARCHAR)\\nQuestion: List the makes of cars that have red color available in year 2020.",
    "Tables: CREATE TABLE cars (car_id INT, make VARCHAR, model VARCHAR, year INT, color VARCHAR)\\nQuestion: Find the make that has the widest variety of colors across all models.",
    "Tables: CREATE TABLE patients (patient_id INT, name VARCHAR, age INT, disease VARCHAR, doctor_id INT)\\nQuestion: What disease does the patient named 'Alice' have?",
    "Tables: CREATE TABLE patients (patient_id INT, name VARCHAR, age INT, disease VARCHAR, doctor_id INT)\\nQuestion: What is the average age of patients with 'Flu'?",
    "Tables: CREATE TABLE patients (patient_id INT, name VARCHAR, age INT, disease VARCHAR, doctor_id INT)\\nQuestion: Count the number of patients for each doctor_id.",
    "Tables: CREATE TABLE patients (patient_id INT, name VARCHAR, age INT, disease VARCHAR, doctor_id INT)\\nQuestion: Find the doctor_id who treats patients with the highest average age.",
    "Tables: CREATE TABLE hospitals (hospital_id INT, name VARCHAR, city VARCHAR, capacity INT)\\nQuestion: What is the capacity of the hospital named 'City Hospital'?",
    "Tables: CREATE TABLE hospitals (hospital_id INT, name VARCHAR, city VARCHAR, capacity INT)\\nQuestion: List the hospitals in 'Boston' ordered by capacity.",
    "Tables: CREATE TABLE hospitals (hospital_id INT, name VARCHAR, city VARCHAR, capacity INT)\\nQuestion: Show the cities that have a total hospital capacity of more than 1000.",
    "Tables: CREATE TABLE hospitals (hospital_id INT, name VARCHAR, city VARCHAR, capacity INT)\\nQuestion: Find the city with the largest difference in capacity between its largest and smallest hospital.",
    "Tables: CREATE TABLE countries (country_id INT, name VARCHAR, continent VARCHAR, population INT)\\nQuestion: What is the population of 'France'?",
    "Tables: CREATE TABLE countries (country_id INT, name VARCHAR, continent VARCHAR, population INT)\\nQuestion: Show the total population of countries in 'Europe'.",
    "Tables: CREATE TABLE countries (country_id INT, name VARCHAR, continent VARCHAR, population INT)\\nQuestion: List the continents that have more than 10 countries.",
    "Tables: CREATE TABLE countries (country_id INT, name VARCHAR, continent VARCHAR, population INT)\\nQuestion: Find the continent with the highest average country population, excluding countries with less than 1 million people.",
    "Tables: CREATE TABLE cities (city_id INT, name VARCHAR, country_id INT, population INT)\\nQuestion: Show the country_id for the city 'Tokyo'.",
    "Tables: CREATE TABLE cities (city_id INT, name VARCHAR, country_id INT, population INT)\\nQuestion: What is the total population of all cities in country_id 5?",
    "Tables: CREATE TABLE cities (city_id INT, name VARCHAR, country_id INT, population INT)\\nQuestion: Find the country_id that has the most cities listed.",
    "Tables: CREATE TABLE cities (city_id INT, name VARCHAR, country_id INT, population INT)\\nQuestion: List the city names that have a population greater than the average population of all cities in their same country_id.",
    "Tables: CREATE TABLE authors (author_id INT, name VARCHAR, country VARCHAR)\\nQuestion: What country is the author 'J.K. Rowling' from?",
    "Tables: CREATE TABLE authors (author_id INT, name VARCHAR, country VARCHAR)\\nQuestion: Count how many authors are from the 'USA'.",
    "Tables: CREATE TABLE authors (author_id INT, name VARCHAR, country VARCHAR)\\nQuestion: List the countries that have more than 5 authors.",
    "Tables: CREATE TABLE authors (author_id INT, name VARCHAR, country VARCHAR)\\nQuestion: Find the country that has exactly 3 authors whose names start with the letter 'A'.",
    "Tables: CREATE TABLE books (book_id INT, title VARCHAR, author_id INT, genre VARCHAR, publish_year INT)\\nQuestion: What is the genre of the book titled '1984'?",
    "Tables: CREATE TABLE books (book_id INT, title VARCHAR, author_id INT, genre VARCHAR, publish_year INT)\\nQuestion: Show all books published after 2010.",
    "Tables: CREATE TABLE books (book_id INT, title VARCHAR, author_id INT, genre VARCHAR, publish_year INT)\\nQuestion: Find the author_id who has written the most books in the 'Fantasy' genre.",
    "Tables: CREATE TABLE books (book_id INT, title VARCHAR, author_id INT, genre VARCHAR, publish_year INT)\\nQuestion: Find the author_id who has written books in both 'Sci-Fi' and 'Fantasy' genres.",
    "Tables: CREATE TABLE users (user_id INT, username VARCHAR, email VARCHAR, is_active BOOLEAN)\\nQuestion: Is the user with username 'admin' active?",
    "Tables: CREATE TABLE users (user_id INT, username VARCHAR, email VARCHAR, is_active BOOLEAN)\\nQuestion: How many active users are there?",
    "Tables: CREATE TABLE users (user_id INT, username VARCHAR, email VARCHAR, is_active BOOLEAN)\\nQuestion: List the email domains of all active users.",
    "Tables: CREATE TABLE users (user_id INT, username VARCHAR, email VARCHAR, is_active BOOLEAN)\\nQuestion: Find the number of active users who registered with a '@gmail.com' email address.",
    "Tables: CREATE TABLE posts (post_id INT, user_id INT, content VARCHAR, likes INT)\\nQuestion: How many likes does post_id 42 have?",
    "Tables: CREATE TABLE posts (post_id INT, user_id INT, content VARCHAR, likes INT)\\nQuestion: Show the total likes for all posts by user_id 7.",
    "Tables: CREATE TABLE posts (post_id INT, user_id INT, content VARCHAR, likes INT)\\nQuestion: Find the user_id with the highest total number of likes across all their posts.",
    "Tables: CREATE TABLE posts (post_id INT, user_id INT, content VARCHAR, likes INT)\\nQuestion: List the user_ids whose average post likes are greater than the overall average post likes of all users.",
    "Tables: CREATE TABLE teams (team_id INT, name VARCHAR, city VARCHAR, wins INT)\\nQuestion: How many wins does the 'Lakers' team have?",
    "Tables: CREATE TABLE teams (team_id INT, name VARCHAR, city VARCHAR, wins INT)\\nQuestion: Show all teams located in 'Los Angeles'.",
    "Tables: CREATE TABLE teams (team_id INT, name VARCHAR, city VARCHAR, wins INT)\\nQuestion: Find the city with the highest total number of team wins.",
    "Tables: CREATE TABLE teams (team_id INT, name VARCHAR, city VARCHAR, wins INT)\\nQuestion: List the cities that have more than one team, ordered by their total wins in descending order.",
    "Tables: CREATE TABLE players (player_id INT, name VARCHAR, team_id INT, goals INT, age INT)\\nQuestion: What is the age of the player 'Ronaldo'?",
    "Tables: CREATE TABLE players (player_id INT, name VARCHAR, team_id INT, goals INT, age INT)\\nQuestion: How many goals has team_id 10 scored in total?",
    "Tables: CREATE TABLE players (player_id INT, name VARCHAR, team_id INT, goals INT, age INT)\\nQuestion: Find the team_id that has the highest average player age.",
    "Tables: CREATE TABLE players (player_id INT, name VARCHAR, team_id INT, goals INT, age INT)\\nQuestion: Show the names of players who have scored more goals than any other player in their specific age group.",
    "Tables: CREATE TABLE flights (flight_id INT, airline VARCHAR, origin VARCHAR, destination VARCHAR, price FLOAT)\\nQuestion: What is the price of flight_id 205?",
    "Tables: CREATE TABLE flights (flight_id INT, airline VARCHAR, origin VARCHAR, destination VARCHAR, price FLOAT)\\nQuestion: How many flights are departing from 'JFK'?",
    "Tables: CREATE TABLE flights (flight_id INT, airline VARCHAR, origin VARCHAR, destination VARCHAR, price FLOAT)\\nQuestion: Find the airline with the lowest average flight price.",
    "Tables: CREATE TABLE flights (flight_id INT, airline VARCHAR, origin VARCHAR, destination VARCHAR, price FLOAT)\\nQuestion: List the origin and destination pairs that have flights from more than 3 different airlines.",
    "Tables: CREATE TABLE passengers (passenger_id INT, name VARCHAR, flight_id INT, seat VARCHAR)\\nQuestion: What seat does passenger 'Bob' have?",
    "Tables: CREATE TABLE passengers (passenger_id INT, name VARCHAR, flight_id INT, seat VARCHAR)\\nQuestion: How many passengers are on flight_id 300?",
    "Tables: CREATE TABLE passengers (passenger_id INT, name VARCHAR, flight_id INT, seat VARCHAR)\\nQuestion: Find the flight_id with the highest number of passengers.",
    "Tables: CREATE TABLE passengers (passenger_id INT, name VARCHAR, flight_id INT, seat VARCHAR)\\nQuestion: Show the names of passengers who share the exact same name but are on different flights.",
    "Tables: CREATE TABLE restaurants (restaurant_id INT, name VARCHAR, cuisine VARCHAR, rating FLOAT)\\nQuestion: What is the rating of 'Pasta House'?",
    "Tables: CREATE TABLE restaurants (restaurant_id INT, name VARCHAR, cuisine VARCHAR, rating FLOAT)\\nQuestion: Count how many 'Italian' restaurants there are.",
    "Tables: CREATE TABLE restaurants (restaurant_id INT, name VARCHAR, cuisine VARCHAR, rating FLOAT)\\nQuestion: Find the cuisine with the highest average rating.",
    "Tables: CREATE TABLE restaurants (restaurant_id INT, name VARCHAR, cuisine VARCHAR, rating FLOAT)\\nQuestion: List the cuisines that have at least 5 restaurants and an average rating above 4.0.",
    "Tables: CREATE TABLE reviews (review_id INT, restaurant_id INT, user_id INT, rating FLOAT, comment VARCHAR)\\nQuestion: Show the comment for review_id 15.",
    "Tables: CREATE TABLE reviews (review_id INT, restaurant_id INT, user_id INT, rating FLOAT, comment VARCHAR)\\nQuestion: What is the average rating given by user_id 99?",
    "Tables: CREATE TABLE reviews (review_id INT, restaurant_id INT, user_id INT, rating FLOAT, comment VARCHAR)\\nQuestion: Find the restaurant_id with the most reviews.",
    "Tables: CREATE TABLE reviews (review_id INT, restaurant_id INT, user_id INT, rating FLOAT, comment VARCHAR)\\nQuestion: List the user_ids who have given a 5.0 rating to every single restaurant they reviewed.",
    "Tables: CREATE TABLE teachers (teacher_id INT, name VARCHAR, subject VARCHAR, salary INT)\\nQuestion: What subject does 'Mr. Smith' teach?",
    "Tables: CREATE TABLE teachers (teacher_id INT, name VARCHAR, subject VARCHAR, salary INT)\\nQuestion: Show the total salary paid to 'Math' teachers.",
    "Tables: CREATE TABLE teachers (teacher_id INT, name VARCHAR, subject VARCHAR, salary INT)\\nQuestion: Find the subject with the lowest average teacher salary.",
    "Tables: CREATE TABLE teachers (teacher_id INT, name VARCHAR, subject VARCHAR, salary INT)\\nQuestion: List the names of teachers whose salary is exactly 10% higher than the minimum salary in their subject.",
    "Tables: CREATE TABLE courses (course_id INT, name VARCHAR, teacher_id INT, credits INT)\\nQuestion: How many credits is the 'Algebra' course?",
    "Tables: CREATE TABLE courses (course_id INT, name VARCHAR, teacher_id INT, credits INT)\\nQuestion: How many courses does teacher_id 3 teach?",
    "Tables: CREATE TABLE courses (course_id INT, name VARCHAR, teacher_id INT, credits INT)\\nQuestion: Find the teacher_id who teaches the most total credits.",
    "Tables: CREATE TABLE courses (course_id INT, name VARCHAR, teacher_id INT, credits INT)\\nQuestion: Show the names of courses that share the same name but are taught by different teachers.",
    "Tables: CREATE TABLE doctors (doctor_id INT, name VARCHAR, specialty VARCHAR, hospital_id INT)\\nQuestion: What is the specialty of Dr. House?",
    "Tables: CREATE TABLE doctors (doctor_id INT, name VARCHAR, specialty VARCHAR, hospital_id INT)\\nQuestion: How many 'Cardiology' doctors are there?",
    "Tables: CREATE TABLE doctors (doctor_id INT, name VARCHAR, specialty VARCHAR, hospital_id INT)\\nQuestion: Find the hospital_id that has the most diverse set of specialties.",
    "Tables: CREATE TABLE doctors (doctor_id INT, name VARCHAR, specialty VARCHAR, hospital_id INT)\\nQuestion: List the specialties that are present in every single hospital_id in the database.",
    "Tables: CREATE TABLE animals (animal_id INT, name VARCHAR, species VARCHAR, zoo_id INT)\\nQuestion: What species is the animal named 'Simba'?",
    "Tables: CREATE TABLE animals (animal_id INT, name VARCHAR, species VARCHAR, zoo_id INT)\\nQuestion: How many 'Lion' animals are in zoo_id 1?",
    "Tables: CREATE TABLE animals (animal_id INT, name VARCHAR, species VARCHAR, zoo_id INT)\\nQuestion: Find the zoo_id with the highest count of unique species.",
    "Tables: CREATE TABLE animals (animal_id INT, name VARCHAR, species VARCHAR, zoo_id INT)\\nQuestion: Show the species that have more than 10 animals in zoo_id 2 but less than 5 animals in zoo_id 3.",
    "Tables: CREATE TABLE zoos (zoo_id INT, name VARCHAR, city VARCHAR, area FLOAT)\\nQuestion: What city is the 'Central Zoo' located in?",
    "Tables: CREATE TABLE zoos (zoo_id INT, name VARCHAR, city VARCHAR, area FLOAT)\\nQuestion: What is the total area of all zoos?",
    "Tables: CREATE TABLE zoos (zoo_id INT, name VARCHAR, city VARCHAR, area FLOAT)\\nQuestion: Find the city with the largest total zoo area.",
    "Tables: CREATE TABLE zoos (zoo_id INT, name VARCHAR, city VARCHAR, area FLOAT)\\nQuestion: List the cities that have exactly two zoos, where one zoo's area is double the area of the other.",
    "Question: What is the name of the employee with id 5?",
    "Question: How many employees are in the IT department?",
    "Question: Which department has the highest average salary?",
    "Question: Find the names of employees who earn more than the average salary of their own department.",
    "Question: Show all students named 'John'.",
    "Question: What is the average GPA of students in the 'Computer Science' major?",
    "Question: List the majors that have more than 100 students.",
    "Question: What is the name of the youngest student who has the highest GPA in the 'Physics' major?",
    "Question: What is the price of the product named 'iPhone'?",
    "Question: Show the top 5 most expensive products.",
    "Question: List all categories that have less than 50 items in total stock.",
    "Question: Find the products whose price is higher than the average price of products in their respective category.",
    "Question: Show the order details for order_id 101.",
    "Question: What is the total amount of orders placed on '2023-01-01'?",
    "Question: Which customer has the highest total order amount?",
    "Question: Find the customer_id of the customer who ordered the most distinct products.",
    "Question: What is the rating of the movie 'The Dark Knight'?",
    "Question: Count how many movies were released in 2015.",
    "Question: Show the names of directors who have directed more than 5 movies.",
    "Question: Find the director who has the highest average rating for their movies released after 2000.",
    "Question: Show the color of the car model 'Civic'.",
    "Question: How many 'Toyota' cars are there?",
    "Question: List the makes of cars that have red color available in year 2020.",
    "Question: Find the make that has the widest variety of colors across all models.",
    "Question: What disease does the patient named 'Alice' have?",
    "Question: What is the average age of patients with 'Flu'?",
    "Question: Count the number of patients for each doctor_id.",
    "Question: Find the doctor_id who treats patients with the highest average age.",
    "Question: What is the capacity of the hospital named 'City Hospital'?",
    "Question: List the hospitals in 'Boston' ordered by capacity.",
    "Question: Show the cities that have a total hospital capacity of more than 1000.",
    "Question: Find the city with the largest difference in capacity between its largest and smallest hospital.",
    "Question: What is the population of 'France'?",
    "Question: Show the total population of countries in 'Europe'.",
    "Question: List the continents that have more than 10 countries.",
    "Question: Find the continent with the highest average country population, excluding countries with less than 1 million people.",
    "Question: Show the country_id for the city 'Tokyo'.",
    "Question: What is the total population of all cities in country_id 5?",
    "Question: Find the country_id that has the most cities listed.",
    "Question: List the city names that have a population greater than the average population of all cities in their same country_id.",
    "Question: What country is the author 'J.K. Rowling' from?",
    "Question: Count how many authors are from the 'USA'.",
    "Question: List the countries that have more than 5 authors.",
    "Question: Find the country that has exactly 3 authors whose names start with the letter 'A'.",
    "Question: What is the genre of the book titled '1984'?",
    "Question: Show all books published after 2010.",
    "Question: Find the author_id who has written the most books in the 'Fantasy' genre.",
    "Question: Find the author_id who has written books in both 'Sci-Fi' and 'Fantasy' genres.",
    "Question: Is the user with username 'admin' active?",
    "Question: How many active users are there?",
    "Question: List the email domains of all active users.",
    "Question: Find the number of active users who registered with a '@gmail.com' email address.",
    "Question: How many likes does post_id 42 have?",
    "Question: Show the total likes for all posts by user_id 7.",
    "Question: Find the user_id with the highest total number of likes across all their posts.",
    "Question: List the user_ids whose average post likes are greater than the overall average post likes of all users.",
    "Question: How many wins does the 'Lakers' team have?",
    "Question: Show all teams located in 'Los Angeles'.",
    "Question: Find the city with the highest total number of team wins.",
    "Question: List the cities that have more than one team, ordered by their total wins in descending order.",
    "Question: What is the age of the player 'Ronaldo'?",
    "Question: How many goals has team_id 10 scored in total?",
    "Question: Find the team_id that has the highest average player age.",
    "Question: Show the names of players who have scored more goals than any other player in their specific age group.",
    "Question: What is the price of flight_id 205?",
    "Question: How many flights are departing from 'JFK'?",
    "Question: Find the airline with the lowest average flight price.",
    "Question: List the origin and destination pairs that have flights from more than 3 different airlines.",
    "Question: What seat does passenger 'Bob' have?",
    "Question: How many passengers are on flight_id 300?",
    "Question: Find the flight_id with the highest number of passengers.",
    "Question: Show the names of passengers who share the exact same name but are on different flights.",
    "Question: What is the rating of 'Pasta House'?",
    "Question: Count how many 'Italian' restaurants there are.",
    "Question: Find the cuisine with the highest average rating.",
    "Question: List the cuisines that have at least 5 restaurants and an average rating above 4.0.",
    "Question: Show the comment for review_id 15.",
    "Question: What is the average rating given by user_id 99?",
    "Question: Find the restaurant_id with the most reviews.",
    "Question: List the user_ids who have given a 5.0 rating to every single restaurant they reviewed.",
    "Question: What subject does 'Mr. Smith' teach?",
    "Question: Show the total salary paid to 'Math' teachers.",
    "Question: Find the subject with the lowest average teacher salary.",
    "Question: List the names of teachers whose salary is exactly 10% higher than the minimum salary in their subject.",
    "Question: How many credits is the 'Algebra' course?",
    "Question: How many courses does teacher_id 3 teach?",
    "Question: Find the teacher_id who teaches the most total credits.",
    "Question: Show the names of courses that share the same name but are taught by different teachers.",
    "Question: What is the specialty of Dr. House?",
    "Question: How many 'Cardiology' doctors are there?",
    "Question: Find the hospital_id that has the most diverse set of specialties.",
    "Question: List the specialties that are present in every single hospital_id in the database.",
    "Question: What species is the animal named 'Simba'?",
    "Question: How many 'Lion' animals are in zoo_id 1?",
    "Question: Find the zoo_id with the highest count of unique species.",
    "Question: Show the species that have more than 10 animals in zoo_id 2 but less than 5 animals in zoo_id 3.",
    "Question: What city is the 'Central Zoo' located in?",
    "Question: What is the total area of all zoos?",
    "Question: Find the city with the largest total zoo area.",
    "Question: List the cities that have exactly two zoos, where one zoo's area is double the area of the other."
]
levels = [
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (With Schema)",
    "Level 2: Easy (With Schema)",
    "Level 4: Complex (With Schema)",
    "Level 5: Very Complex (With Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)",
    "Level 1: Very Easy (Without Schema)",
    "Level 2: Easy (Without Schema)",
    "Level 4: Complex (Without Schema)",
    "Level 5: Very Complex (Without Schema)"
]

markdown_output = "# 200 SQL Tests Evaluation Report (Hardcoded Version)\n\n"

for i in range(200):
    q = questions[i]
    lvl = levels[i]
    
    payload = {
        "model": model_name,
        "prompt": q,
        "stream": False
    }
    
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(url, data=data, headers={'Content-Type': 'application/json'})
    
    try:
        start_time = time.time()
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode('utf-8'))
            sql_response = result.get("response", "").strip()
            duration = round(time.time() - start_time, 2)
            
            markdown_output += f"### Test {i+1} - {lvl}\n"
            markdown_output += f"**Prompt sent to model:**\n```text\n{q}\n```\n\n"
            markdown_output += f"**Generated SQL ({duration}s):**\n```sql\n{sql_response}\n```\n\n---\n"
            print(f"Tested {i+1}/200: {lvl}")
    except Exception as e:
        print(f"Error on question {i+1}: {e}")

with open("200_tests_report.md", "w") as f:
    f.write(markdown_output)

print("\nFinished! Wrote results to 200_tests_report.md")
